#!/bin/bash
# Shuts down the computer, but closes all graphical windows first

windows=()
terminal_name="termite"
readonly sleep_time=0.1 # Seconds to wait before checking if process has finished

# Add to this dictionary all wrong names, ["wrong_name"]="right_name"
declare -A replace_windows=( ["google-chrome"]="chrome" )

find_running_gui_apps() {
    # Find all active windows except terminals
    windows=( $(xlsclients | awk -v x="$terminal_name" '$2!=x { print $2}') )

    # Replace programs that are listed wrong, since xlsclients returns the wrong name
    for newWindowName in "${!replace_windows[@]}"; do
        for i in "${!windows[@]}"; do
            if [[ ${windows[$i]} == "$newWindowName" ]]; then
                windows[$i]="${replace_windows[$newWindowName]}"
            fi
        done
    done
}

kill_windows(){
    for windowName in "${windows[@]}"
    do
        #pkill "$windowName"
        #if [ $? -eq 0 ]
        if pkill "$windowName"
        then
            echo "Kill $windowName"
        else
            echo "Error: Could not kill $windowName"
        fi
    done
    echo "-> Sent kill message to all ${$windows[@]} windows"
}

check_windows_killed(){
    count=0
    while pkill -0 "$windowName";
    do
        echo "Waiting for $windowName ($(echo "$count $sleep_time" | awk '{printf "%.1f", $1 * $2}')s)"
        sleep $sleep_time
        count=$((++count))

        if $count -gt 70
        then
            echo "$windowName does not stop, send SIGKILL instead of SIGTERM"
            pkill -9 $windowName
        fi
    done
}

find_running_gui_apps
#echo ${windows[@]}
kill_windows
check_windows_killed

shutdown now
