#!/bin/bash
# Shuts down the computer, but closes all in WINDOWS specified programs first

WINDOWS=()
PIDS=()
SLEEP_TIME=0.1 # Seconds to wait before checking if process has finished

# Add to this dictionary all wrong names, ["wrong_name"]="right_name"
declare -A REPLACE_WINDOWS=( ["google-chrome"]="chrome" )

running_gui_apps() {
    WINDOWS=($(xlsclients | awk -v x="$TERMINAL_NAME" '$2!=x { print $2}'))

    # Replace programs that are listed wrong, since xlsclients returns the wrong name
    for newWindowName in "${!REPLACE_WINDOWS[@]}"; do
        for i in "${!WINDOWS[@]}"; do
            if [[ ${WINDOWS[$i]} == "$newWindowName" ]]; then
                WINDOWS[$i]="${REPLACE_WINDOWS[$newWindowName]}"
            fi
        done
    done
}

kill_windows(){
    for windowName in "${WINDOWS[@]}"
    do
        pkill $windowName
        if [ $? -eq 0 ]
        then
            echo "Kill $windowName"
        else
            echo "Error: Could not kill $windowName"
        fi

        count=0
        while pkill -0 $windowName;
        do
            echo "Waiting for $windowName ($(echo "$count $SLEEP_TIME" | awk '{printf "%.1f", $1 * $2}')s)"
            sleep $SLEEP_TIME
            count=$((++count))
        done
    done
}

running_gui_apps
#echo ${WINDOWS[@]}
kill_windows

shutdown now


