#!/bin/bash
# Shuts down the computer, but closes all in WINDOWS specified programs first

WINDOWS=()
PIDS=()
TERMINAL_NAME="termite"
SLEEP_TIME=0.1 #seconds to wait before checking if process has finished

running_gui_apps() {
    #WINDOWS=("chrome" "spotify")
    WINDOWS=($(xlsclients | awk -v x="$TERMINAL_NAME" '$2!=x { print $2}'))

    # Replace google-chrome by chrome, since xlsclients returns the wrong name
    for i in "${!WINDOWS[@]}"; do
        if [[ ${WINDOWS[$i]} == "google-chrome" ]]; then
            WINDOWS[$i]="chrome"
        fi
    done
}

kill_windows(){
    for windowName in "${WINDOWS[@]}"
    do
        pkill $windowName
        if [ $? -eq 0 ]
        then
            echo "Kill $windowName"
        else
            echo "Error: Could not kill $windowName"
        fi

        count=0
        while pkill -0 $windowName;
        do
            echo "Waiting for $windowName ($(echo "$count $SLEEP_TIME" | awk '{printf "%.1f", $1 * $2}')s)"
            sleep $SLEEP_TIME
            count=$((++count))
        done
    done
}

running_gui_apps
count=2
# echo ${WINDOWS[@]}
kill_windows

shutdown now


